"""Mapping backend protocol."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from agentic_memory_nav.common.types import FloatArray, FrameObservation, MappingUpdate, Pose3D


class MappingBackend(Protocol):
    def start(self) -> None: ...

    def update(self, frame: FrameObservation) -> MappingUpdate: ...

    def get_latest_pose(self) -> Pose3D | None: ...

    def get_local_pointcloud(self) -> FloatArray: ...

    def get_global_pointcloud(self) -> FloatArray: ...

    def reset(self) -> None: ...

    def save_state(self, path: Path) -> None: ...

    def load_state(self, path: Path) -> None: ...
