"""Robot backend protocol."""

from __future__ import annotations

from typing import Protocol

from agentic_memory_nav.common.types import (
    ActionIntent,
    ExecutionFeedback,
    FrameObservation,
    Pose3D,
    Vector3,
)


class RobotBackend(Protocol):
    def reset(self) -> None: ...
    def get_state(self) -> Pose3D: ...
    def get_observation(self) -> FrameObservation: ...
    def send_velocity_command(self, vx: float, vy: float, wz: float) -> ExecutionFeedback: ...
    def send_waypoint(self, waypoint: Vector3, intent: ActionIntent) -> ExecutionFeedback: ...
    def stop(self) -> None: ...
    def emergency_stop(self) -> None: ...
    def is_collision(self) -> bool: ...
